// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCChRF3kVlYoAvaSvKwCkKPGIIHx-cBIrw',
    appId: '1:345756593133:web:117f1a61543d258915d5e4',
    messagingSenderId: '345756593133',
    projectId: 'reel-ai-dev-1d16a',
    authDomain: 'reel-ai-dev-1d16a.firebaseapp.com',
    databaseURL: 'https://reel-ai-dev-1d16a-default-rtdb.firebaseio.com',
    storageBucket: 'reel-ai-dev-1d16a.firebasestorage.app',
    measurementId: 'G-WMJ2S8JRF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0IO-JPAGkKjJL-tBRc5xtM6Et4LTPjA',
    appId: '1:345756593133:android:58b6c44c0c58ce6115d5e4',
    messagingSenderId: '345756593133',
    projectId: 'reel-ai-dev-1d16a',
    databaseURL: 'https://reel-ai-dev-1d16a-default-rtdb.firebaseio.com',
    storageBucket: 'reel-ai-dev-1d16a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_o18v7pPGNxdAXOV61GwjDMy1fx8HPOQ',
    appId: '1:345756593133:ios:342d530942dc9a4215d5e4',
    messagingSenderId: '345756593133',
    projectId: 'reel-ai-dev-1d16a',
    databaseURL: 'https://reel-ai-dev-1d16a-default-rtdb.firebaseio.com',
    storageBucket: 'reel-ai-dev-1d16a.firebasestorage.app',
    iosBundleId: 'com.reelai.reelAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_o18v7pPGNxdAXOV61GwjDMy1fx8HPOQ',
    appId: '1:345756593133:ios:342d530942dc9a4215d5e4',
    messagingSenderId: '345756593133',
    projectId: 'reel-ai-dev-1d16a',
    databaseURL: 'https://reel-ai-dev-1d16a-default-rtdb.firebaseio.com',
    storageBucket: 'reel-ai-dev-1d16a.firebasestorage.app',
    iosBundleId: 'com.reelai.reelAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCChRF3kVlYoAvaSvKwCkKPGIIHx-cBIrw',
    appId: '1:345756593133:web:40adeadf2053f09d15d5e4',
    messagingSenderId: '345756593133',
    projectId: 'reel-ai-dev-1d16a',
    authDomain: 'reel-ai-dev-1d16a.firebaseapp.com',
    databaseURL: 'https://reel-ai-dev-1d16a-default-rtdb.firebaseio.com',
    storageBucket: 'reel-ai-dev-1d16a.firebasestorage.app',
    measurementId: 'G-VG1Y7KLL79',
  );
}